version: '3.9'
services:
  db:
    image: mysql:8.0
    # build container restart mysql.
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=clean-dev
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ='Asia/Tokyo'
      # setting locales
      - LANG=C.UTF-8
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_store:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  server:
    build:
      context: ../
    volumes:
      - ../:/go/src/github.com/ha-zu/learn-clean-dev
    ports:
      - 1323:1323
    tty: true

volumes:
  db_store:
